spring:
  h2.console:
    enabled: true
    path: '/console'
  datasource:
    url: 'jdbc:h2:file:./todo-db'
  jpa.hibernate.ddl-auto: create-drop
server.error:
  include-message: always
  include-binding-errors: always
